---
- hosts: slave
  remote_user: root 
  tasks:
    - name: install package
      apt: name={{ item }} state=present
      with_items:
        - rabbitmq-server
      when: ansible_os_family == 'Debian'

    - name: add users
      rabbitmq_user: user=openstack password=rabbit123 tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
      with_items:
        - root
